### ISSUE TITLE
Pressing <tab> does not expand into HTML 

### ISSUE THREAD

**Issue by kg4giy** [sloria/sublime-html5-boilerplate#7]
I have just installed the package via the package control. I type: htmlboiler <tab> and the cursor jumps forward five spaces. Nothing expands. 

Sublime v3 build 3143 on Windows 10.

**Comment by Teleri** [comment]
It currently works with `<html` and choosing `htmlboiler`

At least it does for me. This is definitely not as per the original instruction, which did work before.

**Comment by kg4giy** [comment]
Well, I must not have some assumed property set right because typing `<html` and `tab` does nothing and `<html htmlboiler` and `tab` does nothing.

**Comment by Teleri** [comment]
Hi there, sorry I must add that it seems to only work in a .html file, and not in an unsaved blank file.

**Comment by kg4giy** [comment]
So, did I overlook that part of the instruction somewhere? I don't remember seeing anything about opening a .html file for it to work. That was the magic. Thanks.

**Comment by Teleri** [comment]
Nope, something clearly changed. Trying to figure out what.

**Comment by kg4giy** [comment]
OK. Thanks. At the very least a bug against the documentation until it gets sorted.
